//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int PlaseFines { get; set; }
        public int IdDriver { get; set; }
        public int IdZapis { get; set; }
        public string GosNumber { get; set; }
        public int NumberReg { get; set; }
        public string OtherObjects { get; set; }
        public Nullable<int> Victim { get; set; }
        public string Description { get; set; }
        public string PhotoVan { get; set; }
        public string PhotoTu { get; set; }
        public string PhotoFri { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Licences Licences { get; set; }
        public virtual PlaceFines PlaceFines { get; set; }
    }
}
