//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gibdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int Id { get; set; }
        public string Vin { get; set; }
        public int Manufacturer { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public int Weight { get; set; }
        public int Color { get; set; }
        public int EngineType { get; set; }
        public string TypeOfDrive { get; set; }
    
        public virtual ColorsCar ColorsCar { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual EngineType EngineType1 { get; set; }
        public virtual Manufacture Manufacture { get; set; }
    }
}
